### ISSUE TITLE
Provide unschedule flow command

### ISSUE THREAD

**Issue by arnour** [globocom/azkaban-cli#8]
With azkaban cli we can schedule flows but we can't unchedule.

It would be practical a command just like schedule, using project name and flow name as parameters.

Example:

azkaban schedule {project} {flow} {cron}

azkaban unschedule {project} {flow}

**Comment by aguimaraesduarte** [comment]
The `unschedule` azkaban API command takes as input the scheduleId parameter instead of a project and flow. As such, it would require two get requests to fetch this ID.
After discussing the issue, I am going forward with implementing the `unschedule` command as it is in the API, therefore requiring the user to input the scheduleId for the command.

**Comment by aguimaraesduarte** [comment]
PR: https://github.com/globocom/azkaban-cli/pull/11

**Comment by aguimaraesduarte** [comment]
After discussing further with @ggalves and @arnour , I have refactored the `unschedule` command to receive the project and flow names as inputs in the CLI. The backend will make the necessary GET requests so that it can "translate" the inputs into the scheduleId needed by the API.
https://github.com/globocom/azkaban-cli/pull/12
